spring.application.name=student-management
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration :
server.port=9091
server.servlet.context-path=/student
